# Form implementation generated from reading ui file 'Notification_Dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NotificationDialog(object):
    def setupUi(self, NotificationDialog):
        NotificationDialog.setObjectName("NotificationDialog")
        NotificationDialog.resize(331, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NotificationDialog.sizePolicy().hasHeightForWidth())
        NotificationDialog.setSizePolicy(sizePolicy)
        NotificationDialog.setMinimumSize(QtCore.QSize(300, 120))
        NotificationDialog.setMaximumSize(QtCore.QSize(500, 200))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NotificationDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget = QtWidgets.QWidget(parent=NotificationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msg_lbl = QtWidgets.QLabel(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg_lbl.sizePolicy().hasHeightForWidth())
        self.msg_lbl.setSizePolicy(sizePolicy)
        self.msg_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.msg_lbl.setWordWrap(True)
        self.msg_lbl.setObjectName("msg_lbl")
        self.verticalLayout.addWidget(self.msg_lbl)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addWidget(self.verticalWidget)

        self.retranslateUi(NotificationDialog)
        self.buttonBox.accepted.connect(NotificationDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NotificationDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NotificationDialog)

    def retranslateUi(self, NotificationDialog):
        _translate = QtCore.QCoreApplication.translate
        NotificationDialog.setWindowTitle(_translate("NotificationDialog", "Message window"))
        self.msg_lbl.setText(_translate("NotificationDialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NotificationDialog = QtWidgets.QDialog()
    ui = Ui_NotificationDialog()
    ui.setupUi(NotificationDialog)
    NotificationDialog.show()
    sys.exit(app.exec())
