# Form implementation generated from reading ui file 'Msg_Dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MsgDialog(object):
    def setupUi(self, MsgDialog):
        MsgDialog.setObjectName("MsgDialog")
        MsgDialog.resize(331, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MsgDialog.sizePolicy().hasHeightForWidth())
        MsgDialog.setSizePolicy(sizePolicy)
        MsgDialog.setMinimumSize(QtCore.QSize(300, 120))
        MsgDialog.setMaximumSize(QtCore.QSize(500, 200))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MsgDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget = QtWidgets.QWidget(parent=MsgDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msg_lbl = QtWidgets.QLabel(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg_lbl.sizePolicy().hasHeightForWidth())
        self.msg_lbl.setSizePolicy(sizePolicy)
        self.msg_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.msg_lbl.setWordWrap(True)
        self.msg_lbl.setObjectName("msg_lbl")
        self.verticalLayout.addWidget(self.msg_lbl)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Yes)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addWidget(self.verticalWidget)

        self.retranslateUi(MsgDialog)
        self.buttonBox.accepted.connect(MsgDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(MsgDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MsgDialog)

    def retranslateUi(self, MsgDialog):
        _translate = QtCore.QCoreApplication.translate
        MsgDialog.setWindowTitle(_translate("MsgDialog", "Message window"))
        self.msg_lbl.setText(_translate("MsgDialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MsgDialog = QtWidgets.QDialog()
    ui = Ui_MsgDialog()
    ui.setupUi(MsgDialog)
    MsgDialog.show()
    sys.exit(app.exec())
